[book]
authors = ["blackanger"]
language = "zh"
multilingual = false
src = "src"
title = "Rust 编码规范"

[build]
create-missing = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 2

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
git-repository-url = "https://github.com/Rust-Coding-Guidelines/rust-coding-guidelines-zh"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true
level = 0
